Finish T5 RPE on vanilla attention
This revision uses `tkw.apply_expr` to circumvent type mismatches such as:

```
ValueError: Expected an fx.Node but got <class 'int'>
ValueError: Expected an fx.Node but got <class 'Symbol'>
```

This further requires supporting index_cast in `tkw.cast` and
playgroun/vanialla_attention.py now produces valid IR.

Signed-off-by: Nicolas Vasilache <nicolasvasilache@users.noreply.github.com>