Fix IndexError in replace_aten_scaled_dot_product_flash_attention (#1334)
iree-boo-driver fails with IndexError: tuple index out of range when
running aten::scaled_dot_product_attention:

```
torch._dynamo.exc.BackendCompilerFailed: backend='iree_boo_experimental' raised:
IndexError: tuple index out of range
```

Root cause:

The replace_aten_scaled_dot_product_flash_attention function assumes
dropout_p and is_causal are always passed as positional arguments.

---------

Signed-off-by: Yash Rathore <yrathore@amd.com>
Co-Authored-By: Keshav Vinayak Jha <keshavvinayakjha@gmail.com>