ROCm6.3 PT 2.7 pip install error
Repro:
```
python -m venv ~/.venv/test_rocm6.3_pt2.7
source ~/.venv/test_rocm6.3_pt2.7/bin/activate
pip install -r pytorch-rocm-requirements.txt
```

Root cause in .venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py:
```
            if check(obj, memoryview):
                n = len(obj) * obj.itemsize
                if n >= 2 ** 32:
                    raise ValueError("Memoryview is too large")
                self._pack_bin_header(n)
```

Stack trace:
```
ERROR: Exception:
Traceback (most recent call last):
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 165, in exc_logging_wrapper
    status = run_func(*args)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
    return func(self, options, args)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 339, in run
    requirement_set = resolver.resolve(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 94, in resolve
    result = self._result = resolver.resolve(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
    if not criterion.candidates:
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
    return bool(self._sequence)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
    return any(self)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
    candidate = func()
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 215, in _make_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 288, in __init__
    super().__init__(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 227, in _prepare
    dist = self._prepare_distribution()
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 299, in _prepare_distribution
    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 487, in prepare_linked_requirement
    return self._prepare_linked_requirement(req, parallel_builds)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 532, in _prepare_linked_requirement
    local_file = unpack_url(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 214, in unpack_url
    file = get_http_url(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/operations/prepare.py", line 94, in get_http_url
    from_path, content_type = download(link, temp_dir.path)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/network/download.py", line 146, in __call__
    for chunk in chunks:
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/cli/progress_bars.py", line 304, in _rich_progress_bar
    for chunk in iterable:
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_internal/network/utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 576, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/urllib3/response.py", line 519, in read
    data = self._fp.read(amt) if not fp_closed else b""
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 96, in read
    self._close()
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/cachecontrol/filewrapper.py", line 76, in _close
    self.__callback(result)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/cachecontrol/controller.py", line 331, in cache_response
    self.serializer.dumps(request, response, body),
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/cachecontrol/serialize.py", line 70, in dumps
    return b",".join([b"cc=4", msgpack.dumps(data, use_bin_type=True)])
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/__init__.py", line 35, in packb
    return Packer(**kwargs).pack(o)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py", line 885, in pack
    self._pack(obj)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py", line 864, in _pack
    return self._pack_map_pairs(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py", line 970, in _pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py", line 864, in _pack
    return self._pack_map_pairs(
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py", line 970, in _pack_map_pairs
    self._pack(v, nest_limit - 1)
  File "/home/nico/.venv/test_rocm6.3_pt2.7/lib/python3.10/site-packages/pip/_vendor/msgpack/fallback.py", line 821, in _pack
    raise ValueError("Memoryview is too large")
ValueError: Memoryview is too large
```