[boo driver] Set `PYTORCH_MIOPEN_SUGGEST_NHWC=1` (#1207)
This is necessary for getting NHWC outputs for convolutions when using
the `iree_boo_experimental` backend. I've also added some checks so that
we get an error when we can't get the requested output layout, for
example now `--in_layout NHWC --out_layout NCHW --backend
iree_boo_experimental` gives:
```
$ iree-boo-driver convbfp16 -n 128 -c 384 -H 24 -W 48 -k 384 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --iter 100 --in_layout NHWC --out_layout NCHW --fil_layout NHWC --backend iree_boo_experimental

>>> convbfp16 -n 128 -c 384 -H 24 -W 48 -k 384 -y 1 -x 1 -p 0 -q 0 -u 1 -v 1 -l 1 -j 1 -m conv -g 1 -F 1 -t 1 --iter 100 --in_layout NHWC --out_layout NCHW --fil_layout NHWC

Traceback (most recent call last):
  File "/home/rkayaith/repos/iree-turbine/iree/turbine/kernel/boo/driver/driver.py", line 188, in main
    prof = run(
           ^^^^
  File "/home/rkayaith/repos/iree-turbine/iree/turbine/kernel/boo/driver/driver.py", line 274, in run
    example_results = func(*per_device_args[0])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/rkayaith/repos/iree-turbine/iree/turbine/kernel/boo/exports/signature.py", line 77, in run_and_verify
    self._verify_outputs(result)
  File "/home/rkayaith/repos/iree-turbine/iree/turbine/kernel/boo/op_exports/conv.py", line 425, in _verify_outputs
    raise ValueError(
ValueError: Inferred output layout is not contiguous in requested layout: self.output_layout='NCHW', output.stride()=(442368, 1, 18432, 384)
```