Substitute symbols when computing broadcast index
Without this symbolic sizes for the broadcasting dimension cause an
error:

```
TypeError: cannot determine truth value of Relational:
LOAD_ELEM_PER_THREAD > 1
```